### ISSUE TITLE
編集リクエストがリンク切れ

### ISSUE THREAD

**Issue by Tatsuki-I** [aiya000/aiya000.github.io-old#2]
編集リクエストがリンク切れして404が出ます
全てかは分かりませんが、確認したところStringの記事と入門記事その1に関してはリンク切れが起こっていました

**Comment by aiya000** [comment]
thx !

修正したぞいっ

[commit](https://github.com/aiya000/aiya000.github.io/commit/f4a0c8ce35dddaa8c137a325f2c60e56d8211ead)

**Comment by aiya000** [comment]
ありがとねっ！
