### ISSUE TITLE
古今という表現に関して

### ISSUE THREAD

**Issue by Tatsuki-I** [aiya000/aiya000.github.io-old#3]
編集リクエストがリンク切れしていたのでこちらから失礼します

[ことり、穂乃果と一緒に学ぶHaskell（入門）その5「様々な文字列型とIsStringそしてOverloadedStrings」](http://aiya000.github.io/posts/2017-08-03-learn-haskell-with-muse-happy-birthday-honoka.html)
こちらの記事の

> ことり「古今のHaskellはよくGHC拡張に依存しすぎているって言われたりもするけど、 Haskell98レポート『あらすじ>言語とライブラリ』の章に書いてあるHaskellの理念からして GHC拡張はHaskellの正当な進化系だと思うんだ。 心配ないよ♡」

この文頭の"古今"という表現ですが、恐らく"昨今"の誤植ではないかと思います
本質的ではないところですが、少し気になったのでコメントさせて頂きました

**Comment by aiya000** [comment]
助かる〜〜  
直したぞい！（上のリンクで確認できた）

**Comment by aiya000** [comment]
ありがとな！
